import '@/styles/globals.css'
import type { Metadata } from 'next'

// import Footer from '@/components/layouts/Footer'
// import Header from '@/components/layouts/Header'
import Header from '@/components/layouts/Header'
import { ThemeProvider } from '@/components/theme-provider'
import { i18n } from '@/i18n.config'
import { cn } from '@/lib/utils'
import { cairo, plusJakartaSans } from '@/public/fonts/fonts'
import Footer from '@/components/layouts/Footer'

export const metadata: Metadata = {
  title: 'Patient Management System',
  description: 'Generated by create next app'
}

// for rendering the page with static rendering approach
export function generateStaticParams() {
  return i18n.locales.map(locale => ({ locale }))
}

export default async function RootLayout({
  children,
  params: { locale }
}: Readonly<{
  params: { locale: 'ar' | 'en' }
  children: React.ReactNode
}>) {
  return (
    <html lang={locale} dir={locale === 'ar' ? 'rtl' : 'ltr'}>
      <body
        className={cn(
          'bg-primaryBg text-primaryText flex h-screen max-h-screen min-h-screen flex-col px-24',
          locale === 'ar' ? cairo.className : plusJakartaSans.className
        )}
      >
        <ThemeProvider
          attribute='class'
          defaultTheme='dark'
          enableSystem
          disableTransitionOnChange
        >
          <Header locale={locale} />

          <main className='flex-1'>{children}</main>

          <Footer />
        </ThemeProvider>
      </body>
    </html>
  )
}
